{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <other.demo_allure.TestAllure object at 0x000002C89D974BB0>\n\n    @allure.story(\"测试b\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_b(self):\n        print('test_')\n>       assert False\nE       assert False\n\ndemo_allure.py:34: AssertionError"}, "start": 1646746988637, "stop": 1646746988637, "uuid": "2ab8864d-4c49-46e1-8a5c-e970e9038dfc", "historyId": "1ecfcb43f4ef3bde5ccc3d944b1f2302", "testCaseId": "1d7901090f334c5a1eaead3146631f21", "fullName": "demo_allure.TestAllure#test_b", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "测试b"}, {"name": "feature", "value": "allure测试"}, {"name": "suite", "value": "demo_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "zhh-matebook14"}, {"name": "thread", "value": "17584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "demo_allure"}]}