{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <other.demo_allure.TestAllure object at 0x000001E00FC075B0>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_b(self):\n        print('test_')\n>       assert False\nE       assert False\n\ndemo_allure.py:20: AssertionError"}, "start": 1646746128156, "stop": 1646746128157, "uuid": "d34b2005-2dd3-4ae7-b4ce-3bcb11096207", "historyId": "1ecfcb43f4ef3bde5ccc3d944b1f2302", "testCaseId": "1d7901090f334c5a1eaead3146631f21", "fullName": "demo_allure.TestAllure#test_b", "labels": [{"name": "feature", "value": "allure测试"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "demo_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "zhh-matebook14"}, {"name": "thread", "value": "21016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "demo_allure"}]}