{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <other.demo_allure.TestAllure object at 0x0000014C2BC40A58>\n\n    @allure.story(\"测试b\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_b(self):\n        print('test_')\n>       assert False\nE       assert False\n\ndemo_allure.py:34: AssertionError"}, "start": 1664444184330, "stop": 1664444184330, "uuid": "1f1134f7-722a-4865-93fe-f37999aa1b4f", "historyId": "1ecfcb43f4ef3bde5ccc3d944b1f2302", "testCaseId": "1d7901090f334c5a1eaead3146631f21", "fullName": "demo_allure.TestAllure#test_b", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "测试b"}, {"name": "feature", "value": "allure测试"}, {"name": "suite", "value": "demo_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "LAPTOP-QK39G3L1"}, {"name": "thread", "value": "19948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "demo_allure"}]}